-- AlterTable
ALTER TABLE "Shift" ADD COLUMN "startLatitude" DOUBLE PRECISION,
ADD COLUMN "startLongitude" DOUBLE PRECISION,
ADD COLUMN "endLatitude" DOUBLE PRECISION,
ADD COLUMN "endLongitude" DOUBLE PRECISION;
